import Head from 'next/head'
import {Box, Heading} from '@chakra-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>App | Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Heading size="2xl">Main page</Heading>
      </Box>
    </>
  )
}
