import Head from 'next/head'
import {Box} from '@chakra-ui/react'
import {HomeContent} from '@/components/HomeContent'
import {getServerSession} from 'next-auth/next'
import {authOptions} from '@/config/auth'
import {BASE_URL} from '@/config/defaultValues'

export default function Home({userData, videos}) {
    if (userData) {
        const payload = {
            name: userData.user.name,
            email: userData.user.email,
            password: '123',
            image: userData.user.image,
            signUp: true
        }
        fetch(`${BASE_URL}/api/signin`, {
            method: 'POST',
            body: JSON.stringify(payload),
            headers: {
                'Content-Type': 'application/json'
            }
        })
            .then((res) => res.json())
            .catch((error) => {
                console.error(error)
            })
    }

    return (
        <>
            <Head>
                <title>App | Main</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Box p={{base: 2, md: 4}}>
                <HomeContent videos={videos}/>
            </Box>
        </>
    )
}

export async function getServerSideProps(context) {
    const session = await getServerSession(context.req, context.res, authOptions)
    const userData = session

    const res = await fetch(`${BASE_URL}/api/video?userEmail=${userData?.user?.email}`)
    const videos = await res.json()

    return {
        props: {
            userData,
            videos
        }
    }
}
