import Head from 'next/head'
import {Box, Heading} from '@chakra-ui/react'
import {getServerSession} from 'next-auth/next'
import {authOptions} from '@/config/auth'
import {ProfileContent} from '@/components/ProfileContent'

export default function Profile() {
    return (
        <>
            <Head>
                <title>App | Profile</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Box p={{base: 2, md: 4}}>
                <ProfileContent/>
            </Box>
        </>
    )
}

/*
export async function getServerSideProps(context) {
    const session = await getServerSession(context.req, context.res, authOptions)
    return {
        props: {
            session,
        },
    }
}
*/
