import Head from 'next/head'
import {Box} from '@chakra-ui/react'
import {ProfileContent} from '@/components/ProfileContent'
import {BASE_URL} from '@/config/defaultValues'

export default function Profile({users}) {
    return (
        <>
            <Head>
                <title>App | Profile</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Box p={{base: 2, md: 4}}>
                <ProfileContent users={users}/>
            </Box>
        </>
    )
}

export async function getServerSideProps(context) {
    const res = await fetch(`${BASE_URL}/api/user/all`)
    const users = await res.json()

    return{
        props: {
            users
        }
    }
}
